# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - releases/**
    tags:        
      - v*

env:
  IMAGE_NAME: tle-ui

jobs:
  build:
    runs-on: ubuntu-22.04  # Uses GitHub-hosted runner
    environment: dev
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    outputs:
      image_tag: ${{ steps.variables.outputs.image_tag }}
      env: ${{ steps.variables.outputs.env }}
      repo: ${{ steps.variables.outputs.repo }}
      path_repo: ${{ steps.variables.outputs.path_repo }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: variables
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "env=uat" >> $GITHUB_OUTPUT
            echo "image_tag=uat-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
            echo "repo=titledev/k8s-app-demo-nonprod" >> $GITHUB_OUTPUT
            echo "path_repo=k8s-app-demo-nonprod" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_EVENT_NAME == "push" && $GITHUB_REF == "refs/tags/"* ]]; then
            echo "image_tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
            echo "ref_tag=uat-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
            echo "env=prd" >> $GITHUB_OUTPUT
            echo "repo=miw1513/k8s-calculator-prd" >> $GITHUB_OUTPUT
            echo "path_repo=k8s-calculator-prd" >> $GITHUB_OUTPUT
          else
            echo "image_tag=dev-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
            echo "env=dev" >> $GITHUB_OUTPUT
            echo "repo=titledev/k8s-app-demo-nonprod" >> $GITHUB_OUTPUT
            echo "path_repo=k8s-app-demo-nonprod" >> $GITHUB_OUTPUT
          fi


      - name: Build Rust and Push (Develop)
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'  }}
        env:
          USER_HARBOR: ${{ secrets.USER_HARBOR }}
          PASS_HARBOR: ${{ secrets.PASS_HARBOR }}
          REGISTRY: ${{ secrets.REGISTRY_HARBOR }}
          TAG: ${{ steps.variables.outputs.image_tag }}
        run: |
          echo $PASS_HARBOR | docker login $REGISTRY -u $USER_HARBOR --password-stdin
          docker build -t $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:$TAG .  
          docker push $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:$TAG

      - name: Retag Rust and Push (Uat & Production)
        if: ${{  startsWith(github.ref, 'refs/tags/')  }}
        env:
          USER_HARBOR: ${{ secrets.USER_HARBOR }}
          PASS_HARBOR: ${{ secrets.PASS_HARBOR }}
          REGISTRY: ${{ secrets.REGISTRY_HARBOR }}
          TAG: ${{ steps.variables.outputs.image_tag }}
        run: |
          echo $PASS_HARBOR | docker login $REGISTRY -u $USER_HARBOR --password-stdin
          docker pull $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:${{ steps.variables.outputs.ref_tag }}
          docker tag $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:${{ steps.variables.outputs.ref_tag }} $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:$TAG
          docker push $REGISTRY/kubernetes-workshop/${{ env.IMAGE_NAME }}:$TAG

  trigger:
    needs: build
    # if: ${{ ( github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/' || github.ref == 'refs/heads/main' ) )  }}
    name: Update Tag and Deploy
    runs-on: ubuntu-24.04  # Uses GitHub-hosted runner
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: titledev/${{ needs.build.outputs.path_repo }}
          token: ${{ secrets.AUTH_GIT }}
          path: ${{ needs.build.outputs.path_repo }}
          ref: main


      - name: Update image from registry
        working-directory: ${{ needs.build.outputs.path_repo }}
        env:
          IMAGE: ${{ needs.build.outputs.image_tag }}
        run: |-
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          for file in $(find ./helm/values -type f -name '*.yaml'); do
            ENV=$(yq e '.ENV' $file)
            if [ "$ENV" = "${{ needs.build.outputs.env }}" ]; then
              yq e -i '.UI.tag = strenv(IMAGE)' $file
            fi
          done
      
      - name: Update repository
        working-directory: ${{ needs.build.outputs.path_repo }}
        run: |-
          git config --global user.email "support@dependabot.com"
          git config --global user.name "dependabot[bot]"
          git add .
          git commit -am "release: ${{ env.IMAGE_NAME }} env: ${{ needs.build.outputs.env }} version: ${{ needs.build.outputs.image_tag }}"
          git push origin main


